name: Pull Request Automation
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:

    - name: Labeler
      uses: actions/labeler@v4
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Conventional Label
      uses: bcoe/conventional-release-labels@v1
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ignored_types: '["chore","pr"]'
        type_labels: '{"feat": "feature", "fix": "fix", "bug": "fix", "doc": "documentation", "ci": "ci", "chore": "chore", "breaking": "breaking", "BREAKING CHANGE": "breaking"}'

  sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.exclusions=**/__test__/**,.github/**/*
              -Dsonar.coverage.exclusions=**/__test__/**,.github/**/*
              -Dsonar.organization=paulushcgcj-github
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
              -Dsonar.cobertura.reportPaths=coverage/cobertura-coverage.xml
              -Dsonar.project.monorepo.enabled=false
              -Dsonar.projectKey=paulushcgcj_simple-front
              -Dsonar.sources=.
              -Dsonar.tests=src/__test__/components